name = "Easy Docs"
license = "MIT"
licenselink = "LiquidX.store"
description = "Easy, all-in-one beautiful documentation website including a customizable homepage and blog. Super fast, empowering you to focus on your content."

homepage = "LiquidX.store"
demosite = "LiquidX.store"

tags = ["landing", "docs", "blog", "responsive", "minimal", "light", "dark", "multilingual", "dark mode", "tailwind", "company", "gallery"]
features = ["secure", "fast", "search", "dark mode", "widgets"]

# If the theme has a single author
[author]
  name = "LiquidX Solutions"
  homepage = "https://LiquidX.store"
